services:
  db:
    container_name: arj-dev-db
    restart: on-failure
    stdin_open: true
    env_file: .env
    build:
      context: ./docker/images/db
      dockerfile: Dockerfile
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  api:
    container_name: arj-dev-api
    restart: on-failure
    stdin_open: true
    env_file: .env
    build:
      context: ./docker/images/python
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/usr/src/app
    ports:
      - "$API_PORT_EXTERNAL:$API_PORT_INTERNAL"
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_dev_data:
